name: cart_repository
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.5
  meta: ^1.8.0
  uuid: ^3.0.7
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
