name: restaurant
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  bloc: ^8.1.2
  collection: ^1.17.1
  dotted_line: ^3.1.0
  equatable: ^2.0.5
  firebase_core: ^2.13.1
  flutter:
    sdk: flutter
  common:
    path: ../../packages/common
  food_repository:
    path: ../../packages/food_repository
  restaurant_repository:
    path: ../../packages/restaurant_repository
  cart_repository:
    path: ../../packages/cart_repository
  preference_repository:
    path: ../../packages/preference_repository
  flutter_bloc: ^8.1.3
  flutter_slidable: ^3.0.0
  flutter_svg: ^2.0.6
  go_router: ^7.1.1
  ionicons: ^0.2.2
  provider: ^6.0.5
  country_picker: ^2.0.20
  flutter_time_picker_spinner: ^2.0.0
  image_picker: ^0.8.4+4
  formz: ^0.6.0
  form_inputs:
    path: ../../packages/form_inputs
  cuisine_repository:
    path: ../../packages/cuisine_repository
  fluttertoast: ^8.2.2
  firebase_storage: ^11.2.2
  intl: ^0.17.0
  easy_mask: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
