name: client
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  bloc: ^8.1.2
  collection: ^1.17.1
  dotted_line: ^3.1.0
  equatable: ^2.0.5
  firebase_core: ^2.13.1
  flutter:
    sdk: flutter
  common:
    path: ../../packages/common
  food_repository:
    path: ../../packages/food_repository
  restaurant_repository:
    path: ../../packages/restaurant_repository
  cart_repository:
    path: ../../packages/cart_repository
  preference_repository:
    path: ../../packages/preference_repository
  authentication_repository:
    path: ../../packages/authentication_repository
  category_repository:
    path: ../../packages/category_repository
  menu_repository:
    path: ../../packages/menu_repository
  cuisine_repository:
    path: ../../packages/cuisine_repository
  form_inputs:
    path: ../../packages/form_inputs
  user_repository:
    path: ../../packages/user_repository
  flutter_bloc: ^8.1.3
  flutter_slidable: ^3.0.0
  flutter_svg: ^2.0.6
  go_router: ^7.1.1
  ionicons: ^0.2.2
  provider: ^6.0.5
  flutter_paypal: ^0.2.0
  paypal_sdk: ^1.0.7
  formz: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
